# Generated by Django 5.1 on 2024-11-14 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='classified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tumor_type',
            field=models.CharField(blank=True, choices=[('0', 'not_classified'), ('1', 'glioma'), ('2', 'meningioma'), ('3', 'pituitary'), ('4', 'no_tumoe')], max_length=20),
        ),
    ]
