# Generated by Django 5.1 on 2024-11-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_classified_by_alter_image_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tumor_type',
            field=models.CharField(blank=True, choices=[('0', 'not_classified'), ('1', 'glioma'), ('2', 'meningioma'), ('3', 'pituitary'), ('4', 'no_tumoe')], max_length=20, null=True),
        ),
    ]
