# Generated by Django 5.1 on 2024-11-14 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_classified_by_alter_image_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.DecimalField(decimal_places=7, max_digits=7)),
                ('pytorch_model', models.FileField(upload_to='MlModels')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='reports')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_tumor_prob', models.DecimalField(decimal_places=7, max_digits=7)),
                ('pituitary_prob', models.DecimalField(decimal_places=7, max_digits=7)),
                ('meningioma_prob', models.DecimalField(decimal_places=7, max_digits=7)),
                ('glioma_prob', models.DecimalField(decimal_places=7, max_digits=7)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='api.image')),
                ('ml_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='api.mlmodel')),
                ('usage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='api.usage')),
            ],
        ),
    ]
