# Generated by Django 5.1 on 2024-11-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_image_photo_alter_patient_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
