# Generated by Django 5.1 on 2024-11-16 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(default=213142, unique=True, validators=[django.core.validators.RegexValidator('^.{256}$', message='Hash musi zawierać dokładnie 256 cyfr.')]),
            preserve_default=False,
        ),
    ]
