# Generated by Django 5.1 on 2024-11-16 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='glioma_prob',
            field=models.DecimalField(decimal_places=7, max_digits=8),
        ),
        migrations.AlterField(
            model_name='classification',
            name='meningioma_prob',
            field=models.DecimalField(decimal_places=7, max_digits=8),
        ),
        migrations.AlterField(
            model_name='classification',
            name='no_tumor_prob',
            field=models.DecimalField(decimal_places=7, max_digits=8),
        ),
        migrations.AlterField(
            model_name='classification',
            name='pituitary_prob',
            field=models.DecimalField(decimal_places=7, max_digits=8),
        ),
        migrations.AlterField(
            model_name='image',
            name='hash',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^.{64}$', message='Hash musi zawierać dokładnie 64 znaków.')]),
        ),
    ]
