# Generated by Django 5.1 on 2024-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_classification_glioma_prob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='glioma_prob',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='meningioma_prob',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='no_tumor_prob',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='pituitary_prob',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
