# Generated by Django 5.1 on 2024-12-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_classification_glioma_prob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='ml_model',
        ),
        migrations.DeleteModel(
            name='MlModel',
        ),
    ]
